### ISSUE TITLE
pb de "push"

### ISSUE THREAD

**Issue by daclavel** [yaucheres/puckmanager#6]
J'ai des soucis pour pousser mon code!!

MacBook-Air-de-Joan:puckManagerGithub jojolapin$   git push --set-upstream origin master
Username for 'https://github.com': daclavel
Password for 'https://daclavel@github.com': 
To https://github.com/yaucheres/puckmanager.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/yaucheres/puckmanager.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details

**Comment by yaucheres** [comment]
Fait un gît pull, tu n es pas à jour par rapport à l'origine

**Comment by daclavel** [comment]
je l'avais deja fait...

MacBook-Air-de-Joan:puckManagerGithub jojolapin$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

**Comment by daclavel** [comment]
c'est un pb de branche! Je pense...

**Comment by yaucheres** [comment]
Yo , Tu peux m'envoyer le resultat des commandes suivantes  : 
git status
git branch -a

**Comment by daclavel** [comment]
>>>git status

On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Archive.zip

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by daclavel** [comment]
>>git branch -a

* master
  remotes/origin/daclavel-patch-1
  remotes/origin/master
